name: GeneInvestigator
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - hyphy=2.5.31 
  - iqtree=2.1.2
  - snakemake=6.3.0
  - stephenshank::tn93=1.0.7
  - altair=4.1
  - altair_saver=0.5.0
  - biopython=1.78
  - jupyterlab>=3
  - mafft=7.475
  - python=3.8
  - pandas=1.2.4
  - mamba
